# Generated by Django 3.2.3 on 2021-05-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('calorie', models.IntegerField(default=0)),
                ('picture', models.URLField()),
                ('link', models.URLField()),
                ('judge', models.IntegerField(default=0)),
            ],
        ),
    ]
